# Generated by Django 2.2.6 on 2020-05-05 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='todo.Priority'),
            preserve_default=False,
        ),
    ]
