# Generated by Django 2.2.6 on 2020-05-12 02:36

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
